version: '3.8'

services: 
  database:
    container_name: postgres
    image: postgres
    environment:
        POSTGRES_PASSWORD: nagmani 
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 10s
      retries: 10 

  backend:
    container_name: backend
    build:
      context: . 
      dockerfile: Dockerfile

    environment:
      DATABASE_URL: "postgresql://postgres:nagmani@database:5432/postgres"
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 1s
      timeout: 10s
      retries: 10 

  test:
    container_name: test
    build: 
     context: . 
     dockerfile: Dockerfile.test

    depends_on:
      backend:
        condition: service_healthy
